packages:
  - packages/*
  - sites/*

catalog:
  "@sveltejs/kit": ^2.42.0
  "@sveltejs/vite-plugin-svelte": ^6.2.0
  "@types/node": ^20.19.16
  svelte: ^5.38.10
  svelte-check: ^4.3.1
  typescript: ^5.9.2
  vite: ^7.1.5
  vitest: ^3.2.4

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - msw
  - workerd
